<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/02/14 23:03:41

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=apps;host=mysql',
  'username' => 'root',
  'password' => 'root',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
